package FrontEnd;

import Expr.Parser;
import java.awt.Color;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter.HighlightPainter;

public class Form extends javax.swing.JFrame {
    private Parser parser;

    public Form() {
        initComponents();

        textField.setText("");
        btnEvaluar.setText("Evaluar");
        labelError.setText("");

        parser = new Parser() {
            @Override
            public void comunicarError(String errorMsj, int pos, String lexema) {
                resaltar(pos, lexema.length());
            }
        };
    }

    private void resaltar(int pos, int longitud) {
        desResaltar();
        HighlightPainter colorResaltado = new DefaultHighlighter.DefaultHighlightPainter(Color.PINK);

        try {
            textField.getHighlighter().addHighlight(pos, pos + longitud, colorResaltado);
        } catch (Exception e) {
        }
    }

    private void desResaltar() {
        textField.getHighlighter().removeAllHighlights();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField = new javax.swing.JTextField();
        btnEvaluar = new javax.swing.JButton();
        labelError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");

        textField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        textField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textField.setText("textField");
        textField.setToolTipText("");
        textField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldFocusGained(evt);
            }
        });

        btnEvaluar.setText("btnEvaluar");
        btnEvaluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvaluarClick(evt);
            }
        });

        labelError.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelError.setForeground(new java.awt.Color(255, 0, 0));
        labelError.setText("labelError");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelError)
                                        .addComponent(btnEvaluar)
                                        .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, 262,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(81, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEvaluar)
                                .addGap(32, 32, 32)
                                .addComponent(labelError)
                                .addContainerGap(141, Short.MAX_VALUE)));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEvaluarClick(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEvaluarClick
        float r = parser.evaluar(textField.getText());

        if (parser.hayError()) {
            parser.comunicarError(); // Resaltar el error en el textField
            labelError.setText(parser.getErrorMsj());
        } else { // No hubo error
            textField.setText(niceFloat(r)); // Poner el resultado en el textField
            labelError.setText("");
        }

    }// GEN-LAST:event_btnEvaluarClick

    private void textFieldFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_textFieldFocusGained
        desResaltar();
    }// GEN-LAST:event_textFieldFocusGained

    private String niceFloat(float r) { // Quitar el punto decimal (si es posible)
        int e = (int) r;
        if (e == r)
            return "" + e;

        return "" + r;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEvaluar;
    private javax.swing.JLabel labelError;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables
}
